#Spring application settings
spring:
  application:
    name: Medication-service
  profiles:
    active: dev
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/healthsmartdb_medication
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


